apiVersion: v1
kind: Pod
metadata:
  name: redis-pod2
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    -  mountPath: "/my-data"
       name: "my-hostpath-vol"
    resources:
      limits: # limite de recursos utilizado no pod
        memory: "128Mi"
        cpu: "500m"

  volumes:
  - name: "my-hostpath-vol"
    hostPath:
      path: "/var/lib/2-persist"
