apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:

  - name: apache-container
    image: httpd
    resources:
      requests: # Parametros de inicialização dos recursos
        cpu: "500m"
        memory: "128Mi"
      limits: # Parametros dos limites dos recursos
        cpu: "1000m"
        memory: "256Mi"

  - name: redis-container
    image: redis
    resources: # Parametros de inicialização dos recursos
      requests:
        cpu: "400m"
        memory: "64Mi"
      limits: # Parametros dos limites dos recursos
        cpu: "500m"
        memory: "128Mi"
