apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data: # dentro do campo data todos os valores precisam ser codificados em base64
  user: YWRtaW4= #echo -n 'admin' | base64 
  pass: TXktcGFzcy0xMjM= #Decodificando o base64: echo -n 'TXktcGFzcy0xMjM=' | base64 --decode && prinfr "\n"
stringData: # Nao e necessario informacoes em base64
  my-database-name: mysql

