kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-vol-env
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits: # limite de recursos utilizado no pod
         memory: "128Mi"
         cpu: "500m"
    envFrom:
    - secretRef:
        name: my-secret
        optional: true # Tag opcional onde o POD é criado mesmo que o secret não esteja configurado
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/my-vol"
      readOnly: true

  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
      optional: true # Tag opcional onde o volume é criado mesmo que o secret não esteja configurado
