apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.19.2
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi
        readinessProbe: # Inicio da Probe
          httpGet: #  # Protocolo http
            path: / # O caminho que iremos testar
            port: 80 # A porta que iremos testar
          initialDelaySeconds: 10 # Tempo para primeira verificção
          periodSeconds: 10 # De quanto em quanto tempo vamos verificar
          timeoutSeconds: 5 # Tempo para considerar a falha
          successThreshold: 2 # Numero de vezes que vamos testar o container
          failureThreshold: 5 # Erro para reiniciar o container

