apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-server # nome do recurso
spec: # especificação do recurso
  selector: 
    matchLabels: 
      app: nginx 
  replicas: 3 
  template: 
    metadata: 
      labels:
        app: nginx 
      annotations: 
        prometheus.io/scrape: 'true' # habilita o scraping do Prometheus
        prometheus.io/port: '9113' # porta do target
    spec: # especificação do template
      containers: # containers do template 
        - name: nginx
          image: nginx # imagem do container do Nginx
          ports: 
            - containerPort: 80 # porta do container
              name: http
          volumeMounts: 
            - name: nginx-config # nome do volume
              mountPath: /etc/nginx/conf.d/default.conf 
              subPath: nginx.conf 
        - name: nginx-exporter 
          image: 'nginx/nginx-prometheus-exporter:0.11.0' # imagem do container do exporter
          args:
            - '-nginx.scrape-uri=http://localhost/metrics' 
          resources: 
            limits: 
              memory: 128Mi # limite de memória
              cpu: 0.3 # limite de CPU
          ports: # portas do container
            - containerPort: 9113 # porta do container que será exposta
              name: metrics # nome da porta
      volumes: 
        - configMap: 
            defaultMode: 420 # modo padrão do volume
            name: nginx-config # nome do configmap
          name: nginx-config # nome do volume
