apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-svc # nome do serviço
  labels: 
    app: nginx 
spec: 
  ports: # definição da porta do svc 
  - port: 9113 # porta do svc
    name: metrics # nome da porta
  selector: 
    app: nginx