apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.20.2
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.50"
            memory: 128Mi
        livenessProbe: 
          tcpSocket: # Protocolo TCP
            port: 80 # 
          initialDelaySeconds: 10 # Tempo para primeira verificção
          periodSeconds: 10 # De quanto em quanto tempo vamos verificar
          timeoutSeconds: 5 # Tempo para considerar a falha
          failureThreshold: 3 # Erro para reiniciar o container