apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
      tolerations: # Inicia a regra do Tolerations
      - key: gpu
        operator: Equal # Operator igual a gpu
        value: "true" # Valor true
        effect: NoSchedule # Qual é o efeito da Tants