apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
spec :
  type: LoadBalancer
  selector:
    type: web-app
  ports: 
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008
